/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as MultionApi from "..";
export declare class UnprocessableEntityError extends errors.MultionApiError {
    constructor(body: MultionApi.HttpValidationError);
}
