/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccessParams {
    cognitoUsername?: string;
    idToken?: string;
    accessToken?: string;
    refreshToken?: string;
}
