/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface BrowseOutput {
    result: string;
    status: string;
    lastUrl: string;
    content: string;
    screenshot: string;
    sessionId: string;
}
