/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MultionApi from "..";
export interface Message {
    cmd?: string;
    url: string;
    stream?: boolean;
    accessParams?: MultionApi.AccessParams;
    browserParams?: MultionApi.MessageBrowserParams;
    includeScreenshot?: boolean;
}
