/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface RetrieveOutputResponse {
    /** The current status of the session. */
    status: string;
    /** A message providing more details about the session status. */
    message: string;
    /** The URL associated with the session. */
    url: string;
    /** A base64 encoded string of the screenshot, empty if not available. */
    screenshot?: string;
    /** A dictionary of links found on the page. */
    linkDict: Record<string, string>;
}
