/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MultionApi from "..";
export interface SessionCreatedResponse {
    data: MultionApi.SessionCreatedResponseData;
    /** The unique identifier for the session, duplicated for convenience. */
    sessionId: string;
}
