/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MultionApi from "..";
export interface SessionStepSuccessResponse {
    data: MultionApi.SessionStepSuccessResponseData;
    /** The current status of the session. */
    status: string;
}
