/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface RetrieveScreenshotResponseResponse {
    /** response data */
    message: string;
    /** The unique identifier for the session, duplicated for convenience. */
    sessionId: string;
    /** A base64 encoded string of the screenshot, empty if not available. */
    screenshot: string;
}
