/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MultionApi from "../../..";
export interface RetrieveScreenshotResponse {
    response: MultionApi.RetrieveScreenshotResponseResponse;
}
