/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as MultionApi from "../../../../api";
import * as core from "../../../../core";
export declare const CloseSessionResponse: core.serialization.ObjectSchema<serializers.CloseSessionResponse.Raw, MultionApi.CloseSessionResponse>;
export declare namespace CloseSessionResponse {
    interface Raw {
        response: serializers.CloseSessionResponseResponse.Raw;
    }
}
