/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as MultionApi from "../../../../api";
import * as core from "../../../../core";
export declare const ListSessionsResponse: core.serialization.ObjectSchema<serializers.ListSessionsResponse.Raw, MultionApi.ListSessionsResponse>;
export declare namespace ListSessionsResponse {
    interface Raw {
        response: serializers.ListSessionsResponseResponse.Raw;
    }
}
