/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as MultionApi from "../../../../api";
import * as core from "../../../../core";
export declare const ListSessionsResponseResponse: core.serialization.ObjectSchema<serializers.ListSessionsResponseResponse.Raw, MultionApi.ListSessionsResponseResponse>;
export declare namespace ListSessionsResponseResponse {
    interface Raw {
        status: string;
        length: number;
        session_ids: string[];
    }
}
