/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as MultionApi from "../../../../api";
import * as core from "../../../../core";
export declare const RetrieveScreenshotResponseResponse: core.serialization.ObjectSchema<serializers.RetrieveScreenshotResponseResponse.Raw, MultionApi.RetrieveScreenshotResponseResponse>;
export declare namespace RetrieveScreenshotResponseResponse {
    interface Raw {
        message: string;
        session_id: string;
        screenshot: string;
    }
}
