/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as MultionApi from "../../../../api";
import * as core from "../../../../core";
export declare const RetrieveScreenshotResponse: core.serialization.ObjectSchema<serializers.RetrieveScreenshotResponse.Raw, MultionApi.RetrieveScreenshotResponse>;
export declare namespace RetrieveScreenshotResponse {
    interface Raw {
        response: serializers.RetrieveScreenshotResponseResponse.Raw;
    }
}
