"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MultionApiTimeoutError = void 0;
class MultionApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MultionApiTimeoutError.prototype);
    }
}
exports.MultionApiTimeoutError = MultionApiTimeoutError;
