# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .access_params import AccessParams
from .message_browser_params import MessageBrowserParams

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class Message(pydantic.BaseModel):
    cmd: typing.Optional[str]
    url: str
    stream: typing.Optional[bool]
    access_params: typing.Optional[AccessParams]
    browser_params: typing.Optional[MessageBrowserParams]
    include_screenshot: typing.Optional[bool] = pydantic.Field(alias="includeScreenshot")

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
