/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface BrowseInput {
    cmd?: string;
    url: string;
    sessionId?: string;
    maxSteps?: number;
    stream?: boolean;
    includeScreenshot?: boolean;
}
