/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const AccessParams: core.serialization.ObjectSchema<serializers.AccessParams.Raw, MultionApi.AccessParams>;
export declare namespace AccessParams {
    interface Raw {
        cognitoUsername?: string | null;
        idToken?: string | null;
        accessToken?: string | null;
        refreshToken?: string | null;
    }
}
