/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const BrowseOutput: core.serialization.ObjectSchema<serializers.BrowseOutput.Raw, MultionApi.BrowseOutput>;
export declare namespace BrowseOutput {
    interface Raw {
        result: string;
        status: string;
        lastUrl: string;
        content: string;
        screenshot: string;
        session_id: string;
    }
}
