/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const MessageBrowserParams: core.serialization.ObjectSchema<serializers.MessageBrowserParams.Raw, MultionApi.MessageBrowserParams>;
export declare namespace MessageBrowserParams {
    interface Raw {
        height?: number | null;
        width?: number | null;
    }
}
