/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const Message: core.serialization.ObjectSchema<serializers.Message.Raw, MultionApi.Message>;
export declare namespace Message {
    interface Raw {
        cmd?: string | null;
        url: string;
        stream?: boolean | null;
        access_params?: serializers.AccessParams.Raw | null;
        browser_params?: serializers.MessageBrowserParams.Raw | null;
        includeScreenshot?: boolean | null;
    }
}
