/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const RemoteValue: core.serialization.ObjectSchema<serializers.RemoteValue.Raw, MultionApi.RemoteValue>;
export declare namespace RemoteValue {
    interface Raw {
        value: boolean;
    }
}
