/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const RetrieveOutputResponse: core.serialization.ObjectSchema<serializers.RetrieveOutputResponse.Raw, MultionApi.RetrieveOutputResponse>;
export declare namespace RetrieveOutputResponse {
    interface Raw {
        status: string;
        message: string;
        url: string;
        screenshot?: string | null;
        link_dict: Record<string, string>;
    }
}
