/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const RetrieveOutput: core.serialization.ObjectSchema<serializers.RetrieveOutput.Raw, MultionApi.RetrieveOutput>;
export declare namespace RetrieveOutput {
    interface Raw {
        response: serializers.RetrieveOutputResponse.Raw;
    }
}
