/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const SessionStepSuccess: core.serialization.ObjectSchema<serializers.SessionStepSuccess.Raw, MultionApi.SessionStepSuccess>;
export declare namespace SessionStepSuccess {
    interface Raw {
        response: serializers.SessionStepSuccessResponse.Raw;
    }
}
