/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const SessionStepSuccessResponseData: core.serialization.ObjectSchema<serializers.SessionStepSuccessResponseData.Raw, MultionApi.SessionStepSuccessResponseData>;
export declare namespace SessionStepSuccessResponseData {
    interface Raw {
        status: string;
        message: string;
        session_id: string;
        url: string;
        screenshot: string;
    }
}
