/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const SessionCreated: core.serialization.ObjectSchema<serializers.SessionCreated.Raw, MultionApi.SessionCreated>;
export declare namespace SessionCreated {
    interface Raw {
        response: serializers.SessionCreatedResponse.Raw;
    }
}
