/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const SessionCreatedResponse: core.serialization.ObjectSchema<serializers.SessionCreatedResponse.Raw, MultionApi.SessionCreatedResponse>;
export declare namespace SessionCreatedResponse {
    interface Raw {
        data: serializers.SessionCreatedResponseData.Raw;
        session_id: string;
    }
}
