/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MultionApi from "../../api";
import * as core from "../../core";
export declare const SessionStepSuccessResponse: core.serialization.ObjectSchema<serializers.SessionStepSuccessResponse.Raw, MultionApi.SessionStepSuccessResponse>;
export declare namespace SessionStepSuccessResponse {
    interface Raw {
        data: serializers.SessionStepSuccessResponseData.Raw;
        status: string;
    }
}
